"""recreate books table

Revision ID: 02df56eb99b9
Revises: 4f334d5dea8e
Create Date: 2026-01-13 19:39:12.473269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02df56eb99b9'
down_revision: Union[str, Sequence[str], None] = '4f334d5dea8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safe migration: table structure is handled by SQLAlchemy Base.metadata and create_tables.py
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'upload_requests', type_='foreignkey')
    op.drop_constraint(None, 'digital_access', type_='foreignkey')
    op.drop_constraint(None, 'book_subcategory_link', type_='foreignkey')
    op.drop_constraint(None, 'book_permissions', type_='foreignkey')
    op.drop_constraint(None, 'book_copies', type_='foreignkey')
    op.drop_index(op.f('ix_books_title'), table_name='books')
    op.drop_index(op.f('ix_books_serial_number'), table_name='books')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_index(op.f('ix_books_book_number'), table_name='books')
    op.drop_table('books')
    # ### end Alembic commands ###